baseurl = "/"
title = "The Open Goldberg Variations"
canonifyurls = true
theme = "kiera"
paginate = 20
summaryLength = 30
enableEmoji = false
pygmentsCodeFences = true
site_type = "Organization"
org_name = "Open Goldberg Variations"
email = "kimiko@kimiko-piano.com"
favicon = "https://opengoldbergvariations.org/favicon/favicon.ico"
url = "https://opengoldbergvariations.org"


[params]
    tagline = "Bach's Goldberg Variations, played by Kimiko Ishizaka"
    description = "The Open Goldberg Variations (Johann Sebastian Bach, BWV 988), played by Kimiko Ishizaka, are free to download and share. They are governed by the Creative Commons Zero license, which means that they are a part of the public domain, and every use of them is allowed."
    images = ["https://opengoldbergvariations.org/images/open-goldberg-variations.png"] #This is used for opengraph/twitter cards.

[markup.goldmark.renderer]
    unsafe= true

[menu]

  [[menu.main]]
    name = "Free Download"
    weight = -1000
    identifier = "Free Download"
    url = "https://music.kimiko-piano.com/album/j-s-bach-open-goldberg-variations-bwv-988-piano"

  [[menu.main]]
    identifier = "Listen"
    name = "Listen"
    url = "/listen/"
    weight = -120

  [[menu.main]]
    name = "Reviews"
    url = "/review/"
    weight = -110

  [[menu.main]]
    name = "News"
    url = "/news/"
    weight = -100

  [[menu.main]]
    name = "Discover"
    url = "/discover/"
    weight = -90

  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 100

[taxonomies]
  category = "categories"

