"https://{default}/":
  type: upstream
  upstream: "hugo:http"
  cache:
    enabled: true
    default_ttl: 4000
  redirects:
    paths:
      '/node/157':
        to: '/news/boesendorfer-sponsors-open-goldberg-variations/'
        code: 301
      '/kimiko-ishizaka-open-goldberg-variations-pianist':
        to: 'https://kimiko-piano.com'
        code: 301
      '/goldberg-variations-musescore-edition':
        to: 'https://musescore.com/opengoldberg/goldberg-variations'
        code: 301
      '/here-come-mashups-and-visualizations':	
        to: '{default}'
        code: 301
      '/node/191':
        to: '{default}'
        code: 301
      '/teldex-studio-berlin':
        to: '{default}'
        code: 301
      '/download':
        to: '{default}/listen/'
        code: 301
      '/node':
        to: '{default}'
        code: 301
      '/media-gallery':
        to: '{default}'
        code: 301
      '/blog':
        to: '{default}'
        code: 301
      '/freeing-goldberg-variations':
        to: '{default}'
        code: 301  
      '/la-idea-se-llev-cabo-y-el-resultado-es-magn-fico':
        to: '{default}/review/'
        code: 301  
      '/overwhelming-positive-response-release-open-goldberg-variations':
        to: '{default}'
        code: 301  
      '/complete-series-fractal-landscapes-open-goldberg-variations-finished':
        to: 'https://www.youtube.com/watch?v=PtwE0pJKC6g&list=PLltnFtK_6Ww_1xir0-FdTSns8R5fJ0UKI'
        code: 301  
      '/classical-cd-distribution-failing-business-three-major-players-shutting-down':
        to: '{default}'
        code: 301  
      '/fun-stop-motion-response-open-goldberg':
        to: '{default}'
        code: 301  
      '/open-goldberg-variations-cds-are-production':
        to: '{default}'
        code: 301  
      '/js-bach-well-tempered-clavier-volume-1-complete-video-available':
        to: 'https://welltemperedclavier.org'
        code: 301  
      '/kimiko-ishizakas-open-well-tempered-clavier':
        to: 'https://welltemperedclavier.org'
        code: 301  
      '/robert-douglass-interviews-aaron-dunn-musopen-about-setting-chopin-free':
        to: '{default}'
        code: 301  
      '/free-cd-drawing-winners':
        to: '{default}'
        code: 301  
      '/getting-most-out-kickstartercom-pledge-levels':
        to: '{default}'
        code: 301          
      '/review-open-goldberg-variations-and-get-double-cd-free':
        to: '{default}'
        code: 301          
      '/braille-edition-open-goldberg-variations':
        to: '{default}/news/braille-edition-of-the-open-goldberg-variations/'
        code: 301          
      '/otras':
        to: '{default}'
        code: 301            
      '/embedding-musical-scores-web-pages':
        to: '{default}'
        code: 301    
      '/turn-cellphone-dim-lights-and-get-cold-drink-enough-chitchat-time-some-bach':
        to: '{default}/review/'
        code: 301    
      '/concerts':
        to: '{default}'
        code: 301    
      '/concerts.rss':
        to: '{default}'
        code: 301    
      '/soundsnips-free-iphone-app-featuring-open-goldberg-variations':
        to: 'https://www.youtube.com/watch?v=15ezpwCHtJs'
        code: 301    
      '/musescore-releases-free-ipad-app-open-goldberg-variations':
        to: 'https://www.youtube.com/watch?v=15ezpwCHtJs'
        code: 301    
      '/planning-kickstartercom-project-how-high-set-goal':
        to: '{default}'
        code: 301    
      '/reviews':
        to: '{default}/review/'
        code: 301          
      '/help-set-goldberg-variations-freeEn':
        to: '{default}'
        code: 301    
      '/100-goldberg-variations-unboxing':
        to: '{default}'
        code: 301    
      '/amanda-palmer-explains-gratis-music-and-artist-fan-trust':
        to: '{default}'
        code: 301    
      '/open-goldberg-variations-double-cd-now-amazon':
        to: '{default}'
        code: 301    
      '/kimiko-ishizaka-announces-world-tour-performing-bach':
        to: 'https://kimiko-piano.com'
        code: 301    
      '/projectgoldberg-fractal-journey':
        to: 'https://www.youtube.com/watch?v=PtwE0pJKC6g&list=PLltnFtK_6Ww_1xir0-FdTSns8R5fJ0UKI'
        code: 301
      '/kimiko-ishizaka-does-great-job-bring-bachs-composition-life':
        to: '{default}/review/'
        code: 301    
      '/kimiko-ishizaka-plays-well-tempered-clavier-vol-1-ann-arbor-mi':
        to: '{default}'
        code: 301    
      '/partners/imslp-petrucci-music-library':
        to: '{default}'
        code: 301    
      '/opening-aria-it-obvious-going-be-special-recording':
        to: '{default}/review/'
        code: 301    
      '/contact':
        to: '{default}'
        code: 301    
      '/each-voice-speaks-its-own-truth-and-together-they-blend-contemplation':
        to: '{default}/review/'
        code: 301    
      '/recording-goldberg-variations-teldex-studio':
        to: '{default}'
        code: 301    
      '/adrev-contentid-youtube-video-claim-release-form':
        to: '{default}'
        code: 301    
      '/Ulrich':
        to: '{default}'
        code: 301
      '/how-much-money-has-kickstartercom-pumped-music-industry':
        to: '{default}'
        code: 301
      '/kimiko-ishizaka-plays-well-tempered-clavier-vol-1-rockport-ma':
        to: 'https://welltemperedclavier.org'
        code: 301
      '/kimiko-ishizakas-aufnahme-kann-k-nstlerisch-mit-den-besten-einspielungen-auf-modernem-konzertfl-gel':
        to: '{default}/review/'
        code: 301
      '/opening-goldberg':
        to: '{default}'
        code: 301
      '/ms-ishizaka-has-produced-crisp-informed-rendition-variations':
        to: '{default}/review/'
        code: 301
      '/very-honest-and-lucid-recording-which-rather-showcases-impressive-b-sendorfer-imperial-290-ceus':
        to: '{default}/review/'
        code: 301
      '/sit-back-and-realize-how-much-better-music-sounds-once-you-know-you-can-share-it-your-friends':
        to: '{default}/review/'
        code: 301
      '/last-night-when-everyone-else-household-went-bed-i-stayed-listen-copy-public-domain-score':
        to: '{default}/review/'
        code: 301 
      '/case-bachs-goldberg-variations-it-impossible-avoid-long-shadow-still-cast-glenn-goulds-1955-debut':
        to: '{default}/review/'
        code: 301
      '/pianists-recording-very-different-most-ive-listened-over-years':
        to: '{default}/review/'
        code: 301
      '/braille-':
        to: '{default}/news/braille-edition-of-the-open-goldberg-variations/'
        code: 301
"https://www.{default}/":
  type: redirect
  to: "https://{default}/"
