"https://{default}/":
  type: upstream
  upstream: "hugo:http"
  cache:
    enabled: false
  redirects:
    paths:
      '/node/157':
        to: '/news/boesendorfer-sponsors-open-goldberg-variations/'
        code: 301
      '/kimiko-ishizaka-open-goldberg-variations-pianist':
        to: 'https://kimiko-piano.com'
        code: 301
      '/goldberg-variations-musescore-edition':
        to: 'https://musescore.com/opengoldberg/goldberg-variations'
        code: 301
      '/here-come-mashups-and-visualizations':	
        to: '{default}'
        code: 301
      '/node/191':
        to: '{default}'
        code: 301
      '/teldex-studio-berlin':
        to: '{default}'
        code: 301
      '/download':
        to: '{default}/listen/'
        code: 301


"https://www.{default}/":
  type: redirect
  to: "https://{default}/"
