"https://{default}/":
  type: upstream
  upstream: "hugo:http"
  cache:
    enabled: false
  redirects:
    paths:
      '/node/157':
        to: '/news/boesendorfer-sponsors-open-goldberg-variations/'
        code: 301
      '/kimiko-ishizaka-open-goldberg-variations-pianist':
        to: 'https://kimiko-piano.com'
        code: 301
      '/goldberg-variations-musescore-edition':
        to: 'https://musescore.com/opengoldberg/goldberg-variations'
        code: 301
      '/here-come-mashups-and-visualizations':	
        to: '{default}'
        code: 301
      '/node/191':
        to: '{default}'
        code: 301
      '/teldex-studio-berlin':
        to: '{default}'
        code: 301
      '/download':
        to: '{default}/listen/'
        code: 301
      '/node':
        to: '{default}'
        code: 301
      '/media-gallery':
        to: '{default}'
        code: 301
      '/blog':
        to: '{default}'
        code: 301
      '/freeing-goldberg-variations':
        to: '{default}'
        code: 301  
      '/la-idea-se-llev-cabo-y-el-resultado-es-magn-fico':
        to: '{default}/review/'
        code: 301  
      '/overwhelming-positive-response-release-open-goldberg-variations':
        to: '{default}'
        code: 301  
      '/complete-series-fractal-landscapes-open-goldberg-variations-finished':
        to: 'https://www.youtube.com/watch?v=PtwE0pJKC6g&list=PLltnFtK_6Ww_1xir0-FdTSns8R5fJ0UKI'
        code: 301
      '/classical-cd-distribution-failing-business-three-major-players-shutting-down':
        to: '{default}'
        code: 301  
      '/fun-stop-motion-response-open-goldberg':
        to: '{default}'
        code: 301  
      '/open-goldberg-variations-cds-are-production':
        to: '{default}'
        code: 301  
      '/js-bach-well-tempered-clavier-volume-1-complete-video-available':
        to: 'https://welltemperedclavier.org'
        code: 301  
      '/kimiko-ishizakas-open-well-tempered-clavier':
        to: 'https://welltemperedclavier.org'
        code: 301  




"https://www.{default}/":
  type: redirect
  to: "https://{default}/"
