"https://{default}/":
  type: upstream
  upstream: "hugo:http"
  cache:
    enabled: true
    default_ttl: 4000
  redirects:
    paths:
      '/node/157':
        to: '/news/boesendorfer-sponsors-open-goldberg-variations/'
        code: 301
      '/kimiko-ishizaka-open-goldberg-variations-pianist':
        to: 'https://kimiko-piano.com'
        code: 301
      '/goldberg-variations-musescore-edition':
        to: 'https://musescore.com/opengoldberg/goldberg-variations'
        code: 301
<<<<<<< HEAD
      '/here-come-mashups-and-visualizations':	
        to: '/'
=======
      '/node/191':
        to: 'https://opengoldbergvariations.org'
>>>>>>> 977e3444d0e73e08de48108a6c1883c6f9b9a6ce
        code: 301

"https://www.{default}/":
  type: redirect
  to: "https://{default}/"
