"https://{default}/":
  type: upstream
  upstream: "hugo:http"
  redirects:
      paths:
        '/node/157':
          to: '/news/boesendorfer-sponsors-open-goldberg-variations/'
          code: 301 
        '/kimiko-ishizaka-open-goldberg-variations-pianist':
          to: 'https://kimiko-piano.com'
          code: 301
        '/goldberg-variations-musescore-edition':
          to: 'https://musescore.com/opengoldberg/goldberg-variations'
          code: 301
        '/here-come-mashups-and-visualizations':	
          to: '/'
          code: 301
        '/node/191':
          to: '/'
          code: 301
        '/teldex-studio-berlin':
          to: '/'
          code: 301
        '/download':
          to: '/listen/'
          code: 301
        '/node':
          to: '/'
          code: 301
        '/media-gallery':
          to: '/'
          code: 301
        '/blog':
          to: '/'
          code: 301
        '/freeing-goldberg-variations':
          to: '/'
          code: 301  
        '/la-idea-se-llev-cabo-y-el-resultado-es-magn-fico':
          to: '/review/'
          code: 301  
        '/overwhelming-positive-response-release-open-goldberg-variations':
          to: '/'
          code: 301  
        '/complete-series-fractal-landscapes-open-goldberg-variations-finished':
          to: 'https://www.youtube.com/watch?v=PtwE0pJKC6g&list=PLltnFtK_6Ww_1xir0-FdTSns8R5fJ0UKI'
          code: 301
        '/classical-cd-distribution-failing-business-three-major-players-shutting-down':
          to: '/'
          code: 301  
        '/fun-stop-motion-response-open-goldberg':
          to: '/'
          code: 301  
        '/open-goldberg-variations-cds-are-production':
          to: '/'
          code: 301  
        '/js-bach-well-tempered-clavier-volume-1-complete-video-available':
          to: 'https://welltemperedclavier.org'
          code: 301  
        '/kimiko-ishizakas-open-well-tempered-clavier':
          to: 'https://welltemperedclavier.org'
          code: 301  
        '/robert-douglass-interviews-aaron-dunn-musopen-about-setting-chopin-free':
          to: '/'
          code: 301  
        '/free-cd-drawing-winners':
          to: '/'
          code: 301  
        '/getting-most-out-kickstartercom-pledge-levels':
          to: '/'
          code: 301          
        '/review-open-goldberg-variations-and-get-double-cd-free':
          to: '/'
          code: 301          
        '/braille-edition-open-goldberg-variations':
          to: '/news/braille-edition-of-the-open-goldberg-variations/'
          code: 301          
        '/otras':
          to: '/'
          code: 301            
        '/embedding-musical-scores-web-pages':
          to: '/'
          code: 301    
        '/turn-cellphone-dim-lights-and-get-cold-drink-enough-chitchat-time-some-bach':
          to: '/review/'
          code: 301    
        '/concerts':
          to: '/'
          code: 301    
        '/concerts.rss':
          to: '/'
          code: 301
        '/soundsnips-free-iphone-app-featuring-open-goldberg-variations':
          to: 'https://www.youtube.com/watch?v=15ezpwCHtJs'
          code: 301    
        '/musescore-releases-free-ipad-app-open-goldberg-variations':
          to: 'https://www.youtube.com/watch?v=15ezpwCHtJs'
          code: 301    
        '/planning-kickstartercom-project-how-high-set-goal':
          to: '/'
          code: 301    
        '/reviews':
          to: '/review/'
          code: 301          
        '/help-set-goldberg-variations-freeEn':
          to: '/'
          code: 301    
        '/100-goldberg-variations-unboxing':
          to: '/'
          code: 301    
        '/amanda-palmer-explains-gratis-music-and-artist-fan-trust':
          to: '/'
          code: 301    
        '/open-goldberg-variations-double-cd-now-amazon':
          to: '/'
          code: 301    
        '/kimiko-ishizaka-announces-world-tour-performing-bach':
          to: 'https://kimiko-piano.com'
          code: 301    
        '/projectgoldberg-fractal-journey':
          to: 'https://www.youtube.com/watch?v=PtwE0pJKC6g&list=PLltnFtK_6Ww_1xir0-FdTSns8R5fJ0UKI'
          code: 301  
        '/kimiko-ishizaka-plays-well-tempered-clavier-vol-1-ann-arbor-mi':
          to: '/'
          code: 301    
        '/partners/imslp-petrucci-music-library':
          to: '/'
          code: 301
        '/recording-goldberg-variations-teldex-studio':
          to: '/'
          code: 301    
        '/adrev-contentid-youtube-video-claim-release-form':
          to: '/'
          code: 301    
        '/Ulrich':
          to: '/'
          code: 301
        '/how-much-money-has-kickstartercom-pumped-music-industry':
          to: '/'
          code: 301
        '/kimiko-ishizaka-plays-well-tempered-clavier-vol-1-rockport-ma':
          to: 'https://welltemperedclavier.org'
          code: 301
        '/opening-goldberg':
          to: '/'
          code: 301
        '/grincom-publishes-crowdsourced-musical-score-bach-s-goldberg-variations-new-partnership-open':
          to: 'https://music.kimiko-piano.com/album/j-s-bach-open-goldberg-variations-bwv-988-piano'
          code: 301
        '/categories/blindness/':
          to: '/news/braille-edition-of-the-open-goldberg-variations/'
          code: 301

"https://www.{default}/":
  type: redirect
  to: "https://{default}/"
